### ISSUE TITLE
Fix responsive of Overlay component of Differentiation section 

### ISSUE THREAD

**Issue by haboosh92** [ReCoded-Org/IQLBPS-Dilmun#76]
## Description

[Description of the bug or feature]

## Steps to Reproduce

1. fix the styling and size of text on small screens
2. fix the responsive size of video on small screens

**Comment by OmarBassatni97** [comment]
Hiba I checked the video and it is responsive for me. You have a class name in the overlaptext written twice which is font-semibold delete one of them and add the DiffSection file inside the DiffSection folder

**Comment by haboosh92** [comment]
yeah I fixed the responsive issue of the video, but  Kutay wanted the the text to be centered in both axes
